name: Test FRC code

on: [pull_request, workflow_dispatch]
  

permissions:
  contents: read

jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Run unit test
        run: ./gradlew clean test

